
const chartData = {
    option1: [
        {
            Date: '16/2/23',
            Month: 'Jan',
            Year: 2023,
            Supplier: 'Adani',
            Emissions: 200,
            Revenue: 220000,
            ER: 5,
          },
        {
            Date: '16/2/23',
            Month: 'Feb',
            Year: 2023,
            Supplier: 'Adani',
            Emissions: 400,
            Revenue: 220000,
            ER: 9,
          },
          {
            Date: '17/3/23',
            Month: 'Mar',
            Year: 2023,
            Supplier: 'Reliance',
            Emissions: 251,
            Revenue: 254815,
            ER: 11,
          },
          {
            Date: '6/4/23',
            Month: 'Apr',
            Year: 2023,
            Supplier: 'Shaurya Drugs',
            Emissions: 452,
            Revenue: 879797,
            ER: 12,
          },
          {
            Date: '12/5/23',
            Month: 'May',
            Year: 2023,
            Supplier: 'Orlife Healthcare',
            Emissions: 522,
            Revenue: 464464,
            ER: 17,
          },
          {
            Date: '11/8/23',
            Month: 'June',
            Year: 2023,
            Supplier: 'Rezicure Pharmaceuticals',
            Emissions: 724,
            Revenue: 548582,
            ER: 18,
          },
          {
            Date: '6/10/23',
            Month: 'July',
            Year: 2023,
            Supplier: 'Steller Bio Labs',
            Emissions: 624,
            Revenue: 516513,
            ER: 21,
          },
          {
            Date: '8/9/23',
            Month: 'Aug',
            Year: 2023,
            Supplier: 'Ruzette Organics',
            Emissions: 858,
            Revenue: 564651,
            ER: 22,
          },
          {
            Date: '11/8/23',
            Month: 'Sept',
            Year: 2023,
            Supplier: 'Merion Care',
            Emissions: 900,
            Revenue: 565556,
            ER: 25,
          },
          {
            Date: '10/11/23',
            Month: 'Oct',
            Year: 2023,
            Supplier: 'Eskos Pharma',
            Emissions: 624,
            Revenue: 546561,
            ER: 20,
          },
          {
            Date: '16/2/23',
            Month: 'Nov',
            Year: 2023,
            Supplier: 'Adani',
            Emissions: 300,
            Revenue: 220000,
            ER: 18,
          },
          {
            Date: '16/2/23',
            Month: 'Dec',
            Year: 2023,
            Supplier: 'Adani',
            Emissions: 200,
            Revenue: 220000,
            ER: 16,
          },
    ],
    option2: [/* Data for option 2 */],
    
  };
  
  export default chartData;
  